from __future__ import annotations

from datetime import date, datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, EmailStr, Field, field_validator

from schema.enums import BowStyleType, GenderType


class ArcherDemographics(BaseModel):
    date_of_birth: date = Field(..., description="Date of birth (YYYY-MM-DD) in UTC")
    gender: GenderType = Field(description="gender_type enum value")
    bowstyle: BowStyleType = Field(description="bowstyle_type enum value")
    draw_weight: float = Field(
        ..., description="Draw weight in pounds (must be positive)", gt=0, le=200
    )
    club_id: UUID | None = Field(default=None, description="Club id")
    model_config = ConfigDict(title="Archer Demographics", extra="forbid")


class ArcherNamesRequired(BaseModel):
    first_name: str = Field(min_length=1, max_length=100, description="Archer given name")
    last_name: str = Field(min_length=1, max_length=100, description="Archer family name")

    model_config = ConfigDict(title="Archer Names Required", extra="forbid")


class ArcherNamesOptional(BaseModel):
    first_name: str | None = Field(
        default=None, min_length=1, max_length=100, description="Updated given name"
    )
    last_name: str | None = Field(
        default=None, min_length=1, max_length=100, description="Updated family name"
    )

    model_config = ConfigDict(title="Archer Names Optional", extra="forbid")


class ArcherBase(ArcherNamesRequired, ArcherDemographics, BaseModel):
    email: EmailStr = Field(..., description="Unique email address of the archer")
    google_picture_url: str | None = Field(
        default=None, description="Google profile picture URL (optional)"
    )
    google_subject: str = Field(..., description="Google account subject identifier (sub)")
    club_id: UUID | None = Field(default=None, description="This is a placeholder for future use")


class ArcherCreate(ArcherBase):
    model_config = ConfigDict(title="Archer Create", extra="forbid")


class ArcherSet(ArcherNamesOptional, BaseModel):
    gender: GenderType | None = Field(default=None, description="gender_type enum value")
    bowstyle: BowStyleType | None = Field(default=None, description="bowstyle_type enum value")
    google_picture_url: str | None = Field(
        default=None, description="Updated Google profile picture URL"
    )
    last_login_at: datetime | None = Field(default=None, description="Last login timestamp (UTC)")
    draw_weight: float | None = Field(default=None, description="Updated draw weight in pounds")
    club_id: UUID | None = Field(default=None, description="This is a placeholder for future use")

    model_config = ConfigDict(title="Archer Set", extra="forbid")


class ArcherFilter(BaseModel):
    archer_id: UUID | None = Field(
        default=None,
        description="A Universally Unique Identifier generated by the system",
    )
    first_name: str | None = Field(
        default=None, min_length=1, max_length=100, description="Updated given name"
    )
    last_name: str | None = Field(
        default=None, min_length=1, max_length=100, description="Updated family name"
    )
    gender: GenderType | None = Field(default=None, description="Filter by gender")
    bowstyle: BowStyleType | None = Field(default=None, description="Filter by bowstyle")
    last_login_at: datetime | None = Field(default=None, description="Last login timestamp (UTC)")
    created_at: datetime | None = Field(
        default=None,
        description="Registration timestamp (UTC)",
    )
    draw_weight: float | None = Field(default=None, description="Filter by draw weight in pounds")
    club_id: UUID | None = Field(default=None, description="This is a placeholder for future use")
    google_subject: str | None = Field(default=None, description="Filter by Google subject ID")
    model_config = ConfigDict(title="Archer Filter", extra="forbid", populate_by_name=True)


class ArcherUpdate(BaseModel):
    where: ArcherFilter = Field(..., description="Filter criteria to select archers to update")
    data: ArcherSet = Field(..., description="Fields to update on the selected archers")

    model_config = ConfigDict(title="Archer Update", extra="forbid")

    @field_validator("data")
    @classmethod
    def _validate_data_not_empty(cls, v: ArcherSet) -> ArcherSet:
        if len(v.model_fields_set) == 0:
            raise ValueError("data must set at least one field")
        return v

    @field_validator("where")
    @classmethod
    def _validate_where_has_id(cls, v: ArcherFilter) -> ArcherFilter:
        if len(v.model_fields_set) == 0:
            raise ValueError("where must set at least one field")
        elif v.archer_id is None:
            raise ValueError("where.archer_id must be provided")
        return v


class ArcherRead(ArcherBase):
    archer_id: UUID = Field(
        ...,
        description="A Universally Unique Identifier generated by the system",
    )
    last_login_at: datetime = Field(..., description="Last login timestamp (UTC)")
    created_at: datetime = Field(
        ...,
        description="Registration timestamp (UTC)",
    )
    model_config = ConfigDict(title="Archer Read", extra="forbid", populate_by_name=True)

    def get_id(self) -> UUID:
        return self.archer_id


class ArcherId(BaseModel):
    archer_id: UUID = Field(
        ...,
        description="A Universally Unique Identifier generated by the system",
    )
    model_config = ConfigDict(title="Archer ID", extra="forbid", populate_by_name=True)
