from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class SessionsCreate(BaseModel):
    is_opened: bool = Field(..., description="Update open/closed state")
    start_time: datetime = Field(..., description="Session start time (set by the app)")
    location: str = Field(..., max_length=255, description="Location of the session")


class SessionsUpdate(BaseModel):
    is_opened: bool | None = Field(None, description="Update open/closed state")
    location: str | None = Field(None, max_length=255, description="Location of the session")
    start_time: datetime | None = Field(None, description="Session start time")
    end_time: datetime | None = Field(None, description="Session end time")


class SessionsRead(BaseModel):
    session_id: UUID = Field(
        ...,
        alias="id",
        description="A Universally Unique Identifier generated by the system",
    )
    start_time: datetime = Field(..., description="Session start time")
    end_time: datetime | None = Field(None, description="Session end time")
    is_opened: bool = Field(..., description="Is the session currently open?")
    location: str = Field(..., max_length=255, description="Location of the session")

    model_config = ConfigDict(populate_by_name=True, extra="forbid")
