from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class TargetsCreate(BaseModel):
    max_x_coordinate: float = Field(..., description="Max X coordinate of the target")
    max_y_coordinate: float = Field(..., description="Max Y coordinate of the target")
    radius: list[float] = Field(..., description="List of radii for target rings")
    points: list[int] = Field(
        ...,
        description="List of points for each ring (must match radii length)",
    )
    height: float = Field(..., description="Height of the target")
    human_identifier: str = Field(..., max_length=10, description="Human-friendly identifier")
    session_id: UUID = Field(..., description="ID of the session this target belongs to")
    model_config = ConfigDict(extra="forbid")


class TargetsUpdate(BaseModel):
    max_x_coordinate: float | None = Field(
        default=None, description="Max X coordinate of the target"
    )
    max_y_coordinate: float | None = Field(
        default=None, description="Max Y coordinate of the target"
    )
    radius: list[float] | None = Field(default=None, description="List of radii for target rings")
    points: list[int] | None = Field(default=None, description="List of points for each ring")
    height: float | None = Field(default=None, description="Height of the target")
    human_identifier: str | None = Field(
        default=None, description="Optional human-friendly identifier"
    )
    session_id: UUID | None = Field(
        default=None, description="ID of the session this target belongs to"
    )
    model_config = ConfigDict(extra="forbid")


class TargetsFilters(BaseModel):
    max_x_coordinate: float | None = Field(
        default=None, description="Max X coordinate of the target"
    )
    max_y_coordinate: float | None = Field(
        default=None, description="Max Y coordinate of the target"
    )
    height: float | None = Field(default=None, description="Height of the target")
    human_identifier: str | None = Field(
        default=None, description="Optional human-friendly identifier"
    )
    session_id: UUID | None = Field(
        default=None, description="ID of the session this target belongs to"
    )
    model_config = ConfigDict(extra="forbid")


class TargetsRead(TargetsCreate):
    target_id: UUID = Field(
        ...,
        alias="id",
        description="A Universally Unique Identifier generated by the system",
    )
    model_config = ConfigDict(extra="forbid")

    def get_id(self) -> UUID:
        return self.target_id
