# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer
host    all             juanpa          0.0.0.0/0               scram-sha-256
