# Unique settings for the Docker Development Environment
data_directory = '/var/lib/postgresql/data'

# Accept TCP connections from host/other containers in development
listen_addresses = '*'
ssl = off

# Memory allocations for Docker Development (conservatively sized)
shared_buffers = 128MB
effective_cache_size = 512MB

# Timezone settings
timezone = 'America/Toronto'
log_timezone = 'America/Toronto'
