[package]
name = "main_socket"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "*", features = ["full"] }
tokio-tungstenite = "*"
tungstenite = "*"
futures-util = "*"
