/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    readonly '/api/v0/auth/login': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Google One Tap Login
         * @description Verify Google One Tap; start a session if user exists.
         *
         *     - Existing archer: create session, set `arch_stats_auth` HttpOnly cookie, return
         *       AuthAuthenticated (201).
         *     - Unknown subject: return AuthNeedsRegistration (200) with prefilled Google data.
         *
         *     Responses: 201 (authenticated), 200 (needs registration), 401 (invalid token), 400
         *     (missing claims).
         */
        readonly post: operations['google_one_tap_login_api_v0_auth_login_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/auth/google': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Google One Tap Login
         * @description Verify Google One Tap; start a session if user exists.
         *
         *     - Existing archer: create session, set `arch_stats_auth` HttpOnly cookie, return
         *       AuthAuthenticated (201).
         *     - Unknown subject: return AuthNeedsRegistration (200) with prefilled Google data.
         *
         *     Responses: 201 (authenticated), 200 (needs registration), 401 (invalid token), 400
         *     (missing claims).
         */
        readonly post: operations['google_one_tap_login_api_v0_auth_google_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/auth/me': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Current User
         * @description Get the currently authenticated archer from the JWT cookie.
         *
         *     Reads the `arch_stats_auth` cookie, decodes the JWT to extract the archer_id,
         *     fetches the archer details, and returns an AuthAuthenticated response.
         *
         *     Responses: 200 OK (authenticated), 401 (no cookie or invalid token).
         */
        readonly get: operations['get_current_user_api_v0_auth_me_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/auth/logout': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Logout
         * @description Log out: clear cookie and revoke session if present.
         *
         *     - Deletes the `arch_stats_auth` HttpOnly cookie.
         *     - If a valid JWT is supplied, revokes the matching server-side session; otherwise ignored.
         *     - Idempotent: always returns `LogoutResponse(success=True)`.
         *
         *     Responses: 200 OK.
         */
        readonly post: operations['logout_api_v0_auth_logout_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/auth/register': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Register
         * @description Register a new archer (or log in if already exists).
         *
         *     - Verifies Google credential. If an archer with the subject exists, authenticate and set
         *       `arch_stats_auth` cookie (200).
         *     - Otherwise, validate names, create archer, authenticate, and set cookie (201).
         *
         *     Responses: 201 (created + authenticated), 200 (authenticated existing),
         *     401 (invalid token), 400 (invalid Google info or missing names).
         */
        readonly post: operations['register_api_v0_auth_register_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/archer/': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * List Archers
         * @description List archers.
         *
         *     Returns all archers matching default filter.
         *
         *     Responses: 200 OK.
         */
        readonly get: operations['list_archers_api_v0_archer__get'];
        readonly put?: never;
        /**
         * Create Archer
         * @description Create a new archer.
         *
         *     Returns newly created archer id.
         *
         *     Responses: 201 Created.
         */
        readonly post: operations['create_archer_api_v0_archer__post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Update Archer
         * @description Update archer fields matching filter.
         *
         *     Responses: 200 OK, 404 Not Found, 422 Unprocessable Content.
         */
        readonly patch: operations['update_archer_api_v0_archer__patch'];
        readonly trace?: never;
    };
    readonly '/api/v0/archer/{archer_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Archer
         * @description Get a single archer by id.
         *
         *     Responses: 200 OK, 404 Not Found, 422 Unprocessable Content.
         */
        readonly get: operations['get_archer_api_v0_archer__archer_id__get'];
        readonly put?: never;
        readonly post?: never;
        /**
         * Delete Archer
         * @description Delete an archer by id.
         *
         *     Responses: 204 No Content, 404 Not Found, 422 Unprocessable Content.
         */
        readonly delete: operations['delete_archer_api_v0_archer__archer_id__delete'];
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/archer/{archer_id}/open-session': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Open Session For Archer
         * @description Get the open session ID owned by the archer.
         *     Responses: 200 OK
         */
        readonly get: operations['get_open_session_for_archer_api_v0_session_archer__archer_id__open_session_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/archer/{archer_id}/close-session': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Closed Session For Archer
         * @description Get the closed session ID owned by the archer.
         *     Responses: 200 OK
         */
        readonly get: operations['get_closed_session_for_archer_api_v0_session_archer__archer_id__close_session_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/archer/{archer_id}/participating': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Participating Session For Archer
         * @description Get the open session ID of the open session an archer is currently participating in.
         *     Responses: 200 OK, 422 Unprocessable Entity.
         */
        readonly get: operations['get_participating_session_for_archer_api_v0_session_archer__archer_id__participating_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/open': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get All Open Sessions
         * @description List all open sessions.
         *
         *     Responses: 200 OK.
         */
        readonly get: operations['get_all_open_sessions_api_v0_session_open_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Create Session
         * @description Create a session and initial slot assignment.
         *
         *     Responses: 201 Created, 422 Unprocessable Content.
         */
        readonly post: operations['create_session_api_v0_session_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/{session}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Session
         * @description Get session details.
         *
         *     Responses: 200 OK, 404 Not Found.
         */
        readonly get: operations['get_session_api_v0_session__session__get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/re-open': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Re Open Session
         * @description Re-open a closed session.
         *
         *     Responses: 200 OK, 404 Not Found, 422 Unprocessable Content.
         */
        readonly patch: operations['re_open_session_api_v0_session_re_open_patch'];
        readonly trace?: never;
    };
    readonly '/api/v0/session/close': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Close Session
         * @description Close a session.
         *
         *     Responses: 204 No Content, 404 Not Found, 422 Unprocessable Content.
         */
        readonly patch: operations['close_session_api_v0_session_close_patch'];
        readonly trace?: never;
    };
    readonly '/api/v0/session/slot/archer/{archer_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Archer Current Slot
         * @description Get the archer's current active slot assignment (open session and is_shooting = TRUE).
         *
         *     Responses: 200 OK, 404 Not Found.
         */
        readonly get: operations['get_archer_current_slot_api_v0_session_slot_archer__archer_id__get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/slot/{slot}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * Get Slot
         * @description Get active slot assignment details (open session, is_shooting = TRUE).
         *
         *     Responses: 200 OK, 404 Not Found.
         */
        readonly get: operations['get_slot_api_v0_session_slot__slot__get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/slot': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /**
         * Join Session
         * @description Join a session (assign archer to a slot).
         *
         *     Responses: 200 OK, 400 Bad Request.
         */
        readonly post: operations['join_session_api_v0_session_slot_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/session/slot/re-join/{slot_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Re Join Session
         * @description Re-join a session (reassign archer to a slot).
         *
         *     Responses: 200 OK, 400 Bad Request, 403 Forbidden, 422 Unprocessable Content.
         */
        readonly patch: operations['re_join_session_api_v0_session_slot_re_join__slot_id__patch'];
        readonly trace?: never;
    };
    readonly '/api/v0/session/slot/leave/{slot_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        /**
         * Leave Session
         * @description Leave a session (stop archer's slot assignment).
         *
         *     Responses: 200 OK, 400 Bad Request.
         */
        readonly patch: operations['leave_session_api_v0_session_slot_leave__slot_id__patch'];
        readonly trace?: never;
    };
    readonly '/api/v0/shot': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** Create Shot */
        readonly post: operations['create_shot_api_v0_shot_post'];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/shot/by-slot/{slot_id}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Shots By Slot */
        readonly get: operations['get_shots_by_slot_api_v0_shot_by_slot__slot_id__get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/faces': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** List Faces */
        readonly get: operations['list_faces_api_v0_faces_get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly '/api/v0/faces/{face_type}': {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** Get Face */
        readonly get: operations['get_face_api_v0_faces__face_type__get'];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        /** Archer Create */
        readonly ArcherCreate: {
            /**
             * Date Of Birth
             * Format: date
             * @description Date of birth (YYYY-MM-DD) in UTC
             */
            readonly date_of_birth: string;
            /** @description gender_type enum value */
            readonly gender: components['schemas']['GenderType'];
            /** @description bowstyle_type enum value */
            readonly bowstyle: components['schemas']['BowStyleType'];
            /**
             * Draw Weight
             * @description Draw weight in pounds (must be positive)
             */
            readonly draw_weight: number;
            /**
             * Club Id
             * @description This is a placeholder for future use
             */
            readonly club_id?: string | null;
            /**
             * First Name
             * @description Archer given name
             */
            readonly first_name: string;
            /**
             * Last Name
             * @description Archer family name
             */
            readonly last_name: string;
            /**
             * Email
             * Format: email
             * @description Unique email address of the archer
             */
            readonly email: string;
            /**
             * Google Picture Url
             * @description Google profile picture URL (optional)
             */
            readonly google_picture_url?: string | null;
            /**
             * Google Subject
             * @description Google account subject identifier (sub)
             */
            readonly google_subject: string;
        };
        /** Archer Filter */
        readonly ArcherFilter: {
            /**
             * Archer Id
             * @description A Universally Unique Identifier generated by the system
             */
            readonly archer_id?: string | null;
            /**
             * First Name
             * @description Updated given name
             */
            readonly first_name?: string | null;
            /**
             * Last Name
             * @description Updated family name
             */
            readonly last_name?: string | null;
            /** @description Filter by gender */
            readonly gender?: components['schemas']['GenderType'] | null;
            /** @description Filter by bowstyle */
            readonly bowstyle?: components['schemas']['BowStyleType'] | null;
            /**
             * Last Login At
             * @description Last login timestamp (UTC)
             */
            readonly last_login_at?: string | null;
            /**
             * Created At
             * @description Registration timestamp (UTC)
             */
            readonly created_at?: string | null;
            /**
             * Draw Weight
             * @description Filter by draw weight in pounds
             */
            readonly draw_weight?: number | null;
            /**
             * Club Id
             * @description This is a placeholder for future use
             */
            readonly club_id?: string | null;
            /**
             * Google Subject
             * @description Filter by Google subject ID
             */
            readonly google_subject?: string | null;
        };
        /** Archer ID */
        readonly ArcherId: {
            /**
             * Archer Id
             * Format: uuid
             * @description A Universally Unique Identifier generated by the system
             */
            readonly archer_id: string;
        };
        /** Archer Read */
        readonly ArcherRead: {
            /**
             * Date Of Birth
             * Format: date
             * @description Date of birth (YYYY-MM-DD) in UTC
             */
            readonly date_of_birth: string;
            /** @description gender_type enum value */
            readonly gender: components['schemas']['GenderType'];
            /** @description bowstyle_type enum value */
            readonly bowstyle: components['schemas']['BowStyleType'];
            /**
             * Draw Weight
             * @description Draw weight in pounds (must be positive)
             */
            readonly draw_weight: number;
            /**
             * Club Id
             * @description This is a placeholder for future use
             */
            readonly club_id?: string | null;
            /**
             * First Name
             * @description Archer given name
             */
            readonly first_name: string;
            /**
             * Last Name
             * @description Archer family name
             */
            readonly last_name: string;
            /**
             * Email
             * Format: email
             * @description Unique email address of the archer
             */
            readonly email: string;
            /**
             * Google Picture Url
             * @description Google profile picture URL (optional)
             */
            readonly google_picture_url?: string | null;
            /**
             * Google Subject
             * @description Google account subject identifier (sub)
             */
            readonly google_subject: string;
            /**
             * Archer Id
             * Format: uuid
             * @description A Universally Unique Identifier generated by the system
             */
            readonly archer_id: string;
            /**
             * Last Login At
             * Format: date-time
             * @description Last login timestamp (UTC)
             */
            readonly last_login_at: string;
            /**
             * Created At
             * Format: date-time
             * @description Registration timestamp (UTC)
             */
            readonly created_at: string;
        };
        /** Archer Set */
        readonly ArcherSet: {
            /**
             * First Name
             * @description Updated given name
             */
            readonly first_name?: string | null;
            /**
             * Last Name
             * @description Updated family name
             */
            readonly last_name?: string | null;
            /** @description gender_type enum value */
            readonly gender?: components['schemas']['GenderType'] | null;
            /** @description bowstyle_type enum value */
            readonly bowstyle?: components['schemas']['BowStyleType'] | null;
            /**
             * Google Picture Url
             * @description Updated Google profile picture URL
             */
            readonly google_picture_url?: string | null;
            /**
             * Last Login At
             * @description Last login timestamp (UTC)
             */
            readonly last_login_at?: string | null;
            /**
             * Draw Weight
             * @description Updated draw weight in pounds
             */
            readonly draw_weight?: number | null;
            /**
             * Club Id
             * @description This is a placeholder for future use
             */
            readonly club_id?: string | null;
        };
        /** Archer Update */
        readonly ArcherUpdate: {
            /** @description Filter criteria to select archers to update */
            readonly where: components['schemas']['ArcherFilter'];
            /** @description Fields to update on the selected archers */
            readonly data: components['schemas']['ArcherSet'];
        };
        /** Auth Authenticated Response */
        readonly AuthAuthenticated: {
            /** @default authenticated */
            readonly status: components['schemas']['AuthStatus'];
            /**
             * Access Token
             * @description Bearer access token for API requests
             */
            readonly access_token: string;
            /**
             * Expires At
             * Format: date-time
             * @description Access token expiry timestamp (UTC)
             */
            readonly expires_at: string;
            /** @description Authenticated archer profile */
            readonly archer: components['schemas']['ArcherRead'];
        };
        /** Auth Needs Registration Response */
        readonly AuthNeedsRegistration: {
            /** @default needs_registration */
            readonly status: components['schemas']['AuthStatus'];
            /**
             * Google Email
             * Format: email
             * @description Google account email
             */
            readonly google_email: string;
            /**
             * Google Subject
             * @description Google account subject identifier (sub)
             */
            readonly google_subject: string;
            /**
             * Given Name
             * @description Given name from Google (optional)
             */
            readonly given_name?: string | null;
            /**
             * Family Name
             * @description Family name from Google (optional)
             */
            readonly family_name?: string | null;
            /**
             * Given Name Provided
             * @description Whether Google provided a non-empty given_name
             */
            readonly given_name_provided: boolean;
            /**
             * Family Name Provided
             * @description Whether Google provided a non-empty family_name
             */
            readonly family_name_provided: boolean;
            /**
             * Picture Url
             * @description Google profile picture URL
             */
            readonly picture_url?: string | null;
        };
        /** Auth Registration Request */
        readonly AuthRegistrationRequest: {
            /**
             * First Name
             * @description Updated given name
             */
            readonly first_name?: string | null;
            /**
             * Last Name
             * @description Updated family name
             */
            readonly last_name?: string | null;
            /**
             * Date Of Birth
             * Format: date
             * @description Date of birth (YYYY-MM-DD) in UTC
             */
            readonly date_of_birth: string;
            /** @description gender_type enum value */
            readonly gender: components['schemas']['GenderType'];
            /** @description bowstyle_type enum value */
            readonly bowstyle: components['schemas']['BowStyleType'];
            /**
             * Draw Weight
             * @description Draw weight in pounds (must be positive)
             */
            readonly draw_weight: number;
            /**
             * Club Id
             * @description Club id
             */
            readonly club_id?: string | null;
            /**
             * Credential
             * @description Google ID token from One Tap callback
             */
            readonly credential: string;
        };
        /**
         * AuthStatus
         * @enum {string}
         */
        readonly AuthStatus: 'authenticated' | 'needs_registration';
        /**
         * BowStyleType
         * @enum {string}
         */
        readonly BowStyleType: 'recurve' | 'compound' | 'barebow' | 'longbow';
        /** Face Schema */
        readonly Face: {
            /** @description Unique identifier for the face */
            readonly face_type: components['schemas']['FaceType'];
            /**
             * Face Name
             * @description Name of the face
             */
            readonly face_name: string;
            /**
             * Spots
             * @description List of spots on the face
             */
            readonly spots: readonly components['schemas']['Spot'][];
            /**
             * Rings
             * @description List of rings on the face
             */
            readonly rings: readonly components['schemas']['Ring'][];
            /**
             * Viewbox
             * @description SVG viewBox size
             */
            readonly viewBox: number;
            /**
             * Render Cross
             * @description Whether to render the cross in the center
             * @default false
             */
            readonly render_cross: boolean;
        };
        /** Face Minimal Schema */
        readonly FaceMinimal: {
            /** @description Unique identifier for the face */
            readonly face_type: components['schemas']['FaceType'];
            /**
             * Face Name
             * @description Name of the face
             */
            readonly face_name: string;
        };
        /**
         * FaceType
         * @enum {string}
         */
        readonly FaceType:
            | 'wa_40cm_full'
            | 'wa_60cm_full'
            | 'wa_80cm_full'
            | 'wa_122cm_full'
            | 'wa_80cm_6rings'
            | 'wa_122cm_6rings'
            | 'wa_40cm_triple_vertical'
            | 'wa_60cm_triple_triangular'
            | 'none';
        /** Full Slot Assignment Info */
        readonly FullSlotInfo: {
            /**
             * Slot Id
             * Format: uuid
             * @description Unique identifier for the slot assignment
             */
            readonly slot_id: string;
            /**
             * Target Id
             * Format: uuid
             * @description ID of the target this slot is assigned to
             */
            readonly target_id: string;
            /**
             * Archer Id
             * Format: uuid
             * @description ID of the archer assigned to this slot
             */
            readonly archer_id: string;
            /**
             * Session Id
             * Format: uuid
             * @description ID of the session this assignment belongs to
             */
            readonly session_id: string;
            /** @description Type of target face (e.g., '40cm', '80cm') */
            readonly face_type: components['schemas']['FaceType'];
            /** @description Slot letter assigned to the archer (A-D) */
            readonly slot_letter: components['schemas']['SlotLetterType'];
            /**
             * Is Shooting
             * @description Whether the archer is currently shooting in this slot
             */
            readonly is_shooting: boolean;
            /**
             * Created At
             * Format: date-time
             * @description Assignment timestamp (UTC)
             */
            readonly created_at: string;
            /**
             * Lane
             * @description Lane number of the target
             */
            readonly lane: number;
            /**
             * Distance
             * @description Target distance (meters 1-100)
             */
            readonly distance: number;
            /**
             * Slot
             * @description Slot code combining lane and letter (e.g., '1A')
             */
            readonly slot: string;
            /** @description Archer bowstyle copied at join time */
            readonly bowstyle: components['schemas']['BowStyleType'];
            /**
             * Draw Weight
             * @description Archer draw weight copied at join time
             */
            readonly draw_weight: number;
            /**
             * Club Id
             * @description Archer current club at join time
             */
            readonly club_id?: string | null;
        };
        /**
         * GenderType
         * @enum {string}
         */
        readonly GenderType: 'male' | 'female' | 'non_binary' | 'other' | 'unspecified';
        /** Google One Tap Request */
        readonly GoogleOneTapRequest: {
            /**
             * Credential
             * @description Google ID token from One Tap callback
             */
            readonly credential: string;
        };
        /** HTTPValidationError */
        readonly HTTPValidationError: {
            /** Detail */
            readonly detail?: readonly components['schemas']['ValidationError'][];
        };
        /** Logout Response */
        readonly LogoutResponse: {
            /**
             * Success
             * @description Indicates if logout succeeded
             */
            readonly success: boolean;
        };
        /** Ring Schema */
        readonly Ring: {
            /**
             * Data Score
             * @description e.g., 10, 9, 8, ...
             */
            readonly data_score: number;
            /**
             * Fill
             * @description Color of the scoring zone
             */
            readonly fill: string;
            /**
             * R
             * @description Radius of the scoring zone
             */
            readonly r: number;
            /**
             * Stroke
             * @description Color of the outer line
             */
            readonly stroke: string;
            /**
             * Stroke Width
             * @description Thickness of the outer line
             */
            readonly stroke_width: number;
        };
        /** Session Create */
        readonly SessionCreate: {
            /**
             * Owner Archer Id
             * Format: uuid
             * @description Owner archer UUID
             */
            readonly owner_archer_id: string;
            /**
             * Session Location
             * @description Session location label (e.g., range name)
             */
            readonly session_location: string;
            /**
             * Is Indoor
             * @description Wether the session is indoors or not
             * @default false
             */
            readonly is_indoor: boolean;
            /**
             * Is Opened
             * @description Wether the session is open or not
             */
            readonly is_opened: boolean;
            /**
             * Shot Per Round
             * @description Number of shots per round for the current session format
             * @default 6
             */
            readonly shot_per_round: number;
        };
        /** Session ID */
        readonly SessionId: {
            /**
             * Session Id
             * @description Session identifier (UUID)
             */
            readonly session_id?: string | null;
        };
        /** Session Read */
        readonly SessionRead: {
            /**
             * Owner Archer Id
             * Format: uuid
             * @description Owner archer UUID
             */
            readonly owner_archer_id: string;
            /**
             * Session Location
             * @description Session location label (e.g., range name)
             */
            readonly session_location: string;
            /**
             * Is Indoor
             * @description Wether the session is indoors or not
             * @default false
             */
            readonly is_indoor: boolean;
            /**
             * Is Opened
             * @description Wether the session is open or not
             */
            readonly is_opened: boolean;
            /**
             * Shot Per Round
             * @description Number of shots per round for the current session format
             * @default 6
             */
            readonly shot_per_round: number;
            /**
             * Session Id
             * Format: uuid
             * @description Session identifier (UUID)
             */
            readonly session_id: string;
            /**
             * Created At
             * Format: date-time
             * @description Open timestamp (UTC)
             */
            readonly created_at: string;
            /**
             * Closed At
             * @description Closing timestamp (UTC), if any
             */
            readonly closed_at?: string | null;
        };
        /** Shot Create */
        readonly ShotCreate: {
            /**
             * Slot Id
             * Format: uuid
             * @description Slot identifier (UUID) this shot belongs to
             */
            readonly slot_id: string;
            /**
             * X
             * @description X coordinate in millimeters
             */
            readonly x?: number | null;
            /**
             * Y
             * @description Y coordinate in millimeters
             */
            readonly y?: number | null;
            /**
             * Is X
             * @description Indicates if the shot is an 'X' shot
             * @default false
             */
            readonly is_x: boolean;
            /**
             * Score
             * @description Shot score (0..10)
             */
            readonly score?: number | null;
            /**
             * Arrow Id
             * @description Optional arrow identifier (e.g., arrow number or code)
             */
            readonly arrow_id?: string | null;
        };
        /** Shot ID */
        readonly ShotId: {
            /**
             * Shot Id
             * Format: uuid
             * @description Shot identifier (UUID)
             */
            readonly shot_id: string;
        };
        /** Shot Read */
        readonly ShotRead: {
            /**
             * Slot Id
             * Format: uuid
             * @description Slot identifier (UUID) this shot belongs to
             */
            readonly slot_id: string;
            /**
             * X
             * @description X coordinate in millimeters
             */
            readonly x?: number | null;
            /**
             * Y
             * @description Y coordinate in millimeters
             */
            readonly y?: number | null;
            /**
             * Is X
             * @description Indicates if the shot is an 'X' shot
             * @default false
             */
            readonly is_x: boolean;
            /**
             * Score
             * @description Shot score (0..10)
             */
            readonly score?: number | null;
            /**
             * Arrow Id
             * @description Optional arrow identifier (e.g., arrow number or code)
             */
            readonly arrow_id?: string | null;
            /**
             * Shot Id
             * Format: uuid
             * @description Shot identifier (UUID)
             */
            readonly shot_id: string;
            /**
             * Created At
             * Format: date-time
             * @description Creation timestamp (UTC)
             */
            readonly created_at: string;
        };
        /** Slot Assignment Request */
        readonly SlotJoinRequest: {
            /**
             * Archer Id
             * Format: uuid
             * @description ID of the archer to assign to the slot
             */
            readonly archer_id: string;
            /**
             * Session Id
             * Format: uuid
             * @description ID of the session for the assignment
             */
            readonly session_id: string;
            /** @description Type of target face (e.g., '40cm', '80cm') */
            readonly face_type: components['schemas']['FaceType'];
            /**
             * Is Shooting
             * @description Set to True if archer is currently shooting, False otherwise
             * @default true
             */
            readonly is_shooting: boolean;
            /** @description Archer bowstyle copied at join time */
            readonly bowstyle: components['schemas']['BowStyleType'];
            /**
             * Draw Weight
             * @description Archer draw weight copied at join time
             */
            readonly draw_weight: number;
            /**
             * Club Id
             * @description Archer current club at join time
             */
            readonly club_id?: string | null;
            /**
             * Distance
             * @description Requested distance to shoot (meters 1-100)
             */
            readonly distance: number;
        };
        /** Slot Assignment Response */
        readonly SlotJoinResponse: {
            /**
             * Slot Id
             * Format: uuid
             * @description ID of the slot assignment
             */
            readonly slot_id: string;
            /**
             * Slot
             * @description Slot assigned to the archer (1A, 3D, 4B)
             */
            readonly slot: string;
        };
        /**
         * SlotLetterType
         * @enum {string}
         */
        readonly SlotLetterType: 'A' | 'B' | 'C' | 'D';
        /**
         * Spot Schema
         * @description We use offset from center to allocate multiple spots on the same face in relation to
         *     the canvas center. At the same time, x_offset and y_offset are the center of the spot.
         */
        readonly Spot: {
            /**
             * X Offset
             * @description in mm, offset from center
             */
            readonly x_offset: number;
            /**
             * Y Offset
             * @description in mm, offset from center
             */
            readonly y_offset: number;
            /**
             * Diameter
             * @description in mm
             */
            readonly diameter: number;
        };
        /** ValidationError */
        readonly ValidationError: {
            /** Location */
            readonly loc: readonly (string | number)[];
            /** Message */
            readonly msg: string;
            /** Error Type */
            readonly type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    readonly google_one_tap_login_api_v0_auth_login_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['GoogleOneTapRequest'];
            };
        };
        readonly responses: {
            /** @description Archer was authenticated but needs registration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthNeedsRegistration'];
                };
            };
            /** @description Archer authenticated successfully */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthAuthenticated'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly google_one_tap_login_api_v0_auth_google_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['GoogleOneTapRequest'];
            };
        };
        readonly responses: {
            /** @description Archer was authenticated but needs registration */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthNeedsRegistration'];
                };
            };
            /** @description Archer authenticated successfully */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthAuthenticated'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_current_user_api_v0_auth_me_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthAuthenticated'];
                };
            };
        };
    };
    readonly logout_api_v0_auth_logout_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['LogoutResponse'];
                };
            };
        };
    };
    readonly register_api_v0_auth_register_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['AuthRegistrationRequest'];
            };
        };
        readonly responses: {
            /** @description User was already registered */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthAuthenticated'];
                };
            };
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['AuthAuthenticated'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly list_archers_api_v0_archer__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': readonly components['schemas']['ArcherRead'][];
                };
            };
        };
    };
    readonly create_archer_api_v0_archer__post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['ArcherCreate'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['ArcherId'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly update_archer_api_v0_archer__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['ArcherUpdate'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_archer_api_v0_archer__archer_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['ArcherRead'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly delete_archer_api_v0_archer__archer_id__delete: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_open_session_for_archer_api_v0_session_archer__archer_id__open_session_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SessionId'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_closed_session_for_archer_api_v0_session_archer__archer_id__close_session_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': readonly components['schemas']['SessionRead'][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_participating_session_for_archer_api_v0_session_archer__archer_id__participating_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SessionId'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_all_open_sessions_api_v0_session_open_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': readonly components['schemas']['SessionRead'][];
                };
            };
        };
    };
    readonly create_session_api_v0_session_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['SessionCreate'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SessionId'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_session_api_v0_session__session__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly session: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SessionRead'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly re_open_session_api_v0_session_re_open_patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['SessionId'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SessionId'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly close_session_api_v0_session_close_patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['SessionId'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_archer_current_slot_api_v0_session_slot_archer__archer_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly archer_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['FullSlotInfo'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_slot_api_v0_session_slot__slot__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slot: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['FullSlotInfo'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly join_session_api_v0_session_slot_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json': components['schemas']['SlotJoinRequest'];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SlotJoinResponse'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly re_join_session_api_v0_session_slot_re_join__slot_id__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slot_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['SlotJoinResponse'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly leave_session_api_v0_session_slot_leave__slot_id__patch: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slot_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': unknown;
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly create_shot_api_v0_shot_post: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly 'application/json':
                    | components['schemas']['ShotCreate']
                    | readonly components['schemas']['ShotCreate'][];
            };
        };
        readonly responses: {
            /** @description Successful Response */
            readonly 201: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json':
                        | components['schemas']['ShotId']
                        | readonly components['schemas']['ShotId'][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly get_shots_by_slot_api_v0_shot_by_slot__slot_id__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly slot_id: string;
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': readonly components['schemas']['ShotRead'][];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
    readonly list_faces_api_v0_faces_get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': readonly components['schemas']['FaceMinimal'][];
                };
            };
        };
    };
    readonly get_face_api_v0_faces__face_type__get: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly face_type: components['schemas']['FaceType'];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Successful Response */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['Face'];
                };
            };
            /** @description Validation Error */
            readonly 422: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly 'application/json': components['schemas']['HTTPValidationError'];
                };
            };
        };
    };
}
