[package]
name = "shoot_recorder"
edition = "2021"
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
postgres = { workspace = true }
ctrlc = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
