name: Setup Backend Env
description: Sets up uv, syncs backend dependencies, and activates venv

runs:
  using: "composite"
  steps:
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Sync Python deps
      run: |
        cd backend
        uv sync

    - name: Activate virtualenv
      shell: bash
      run: |
        source backend/.venv/bin/activate
