from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ArrowsCreate(BaseModel):
    arrow_id: UUID = Field(
        ...,
        alias="id",
        description="A Universally Unique Identifier generated by the system",
    )
    human_identifier: str = Field(
        ...,
        max_length=10,
        description="Short unique identifier easy to remember",
        examples=["A1", "B", "3", "etc"],
    )
    length: float = Field(
        ...,
        description="Arrow's total length in cm",
        examples=[75.0],
    )
    registration_date: datetime = Field(
        ...,
        description="Date/time when the arrow was registered and ready to use",
    )
    is_programmed: bool = Field(
        ...,
        description="Whether the arrow has been programmed with a UUID",
    )
    is_active: bool = Field(
        default=True,
        description="Whether the arrow is currently active and in use",
    )
    voided_date: datetime | None = Field(
        default=None,
        description="Date/time when the arrow was voided (no longer in use)",
    )
    weight: float | None = Field(
        default=None,
        description="Arrow's weight in grams",
        examples=[20.5],
    )
    diameter: float | None = Field(
        default=None,
        description="Diameter of the arrow in mm",
        examples=[6.2],
    )
    spine: float | None = Field(
        default=None,
        description="Arrow spine (flexibility rating)",
        examples=[500],
    )
    label_position: float | None = Field(
        default=None,
        description="Position of label from nock in cm",
        examples=[10.0],
    )
    model_config = ConfigDict(extra="forbid")


class ArrowsUpdate(BaseModel):
    registration_date: datetime | None = Field(
        default=None,
        description="Date/time when the arrow was registered and ready to use",
    )
    is_programmed: bool | None = Field(
        default=None,
        description="Whether the arrow has been programmed with a UUID",
    )
    is_active: bool | None = Field(
        default=None,
        description="Whether the arrow is currently active and in use",
    )
    voided_date: datetime | None = Field(
        default=None,
        description="Date/time when the arrow was voided (no longer in use)",
    )
    human_identifier: str | None = Field(
        default=None,
        max_length=10,
        description="Short unique identifier easy to remember",
        examples=["A1", "B", "3", "etc"],
    )
    length: float | None = Field(
        default=None,
        description="Arrow's total length in cm",
        examples=[75.0],
    )
    weight: float | None = Field(
        default=None,
        description="Arrow's weight in grams",
        examples=[20.5],
    )
    diameter: float | None = Field(
        default=None,
        description="Diameter of the arrow in mm",
        examples=[6.2],
    )
    spine: float | None = Field(
        default=None,
        description="Arrow spine (flexibility rating)",
        examples=[500],
    )
    label_position: float | None = Field(
        default=None,
        description="Position of label from nock in cm",
        examples=[10.0],
    )
    model_config = ConfigDict(extra="forbid")


class ArrowsFilters(BaseModel):
    arrow_id: UUID | None = Field(default=None, alias="id", description="ID of the arrow")
    registration_date: datetime | None = Field(
        default=None,
        description="Date/time when the arrow was registered and ready to use",
    )
    is_programmed: bool | None = Field(
        default=None,
        description="Whether the arrow has been programmed with a UUID",
    )
    is_active: bool | None = Field(
        default=None,
        description="Whether the arrow is currently active and in use",
    )
    voided_date: datetime | None = Field(
        default=None,
        description="Date/time when the arrow was voided (no longer in use)",
    )
    human_identifier: str | None = Field(
        default=None,
        max_length=10,
        description="Short unique identifier easy to remember",
        examples=["A1", "B", "3", "etc"],
    )
    length: float | None = Field(
        default=None,
        description="Arrow's total length in cm",
        examples=[75.0],
    )
    weight: float | None = Field(
        default=None,
        description="Arrow's weight in grams",
        examples=[20.5],
    )
    diameter: float | None = Field(
        default=None,
        description="Diameter of the arrow in mm",
        examples=[6.2],
    )
    spine: float | None = Field(
        default=None,
        description="Arrow spine (flexibility rating)",
        examples=[500],
    )
    label_position: float | None = Field(
        default=None,
        description="Position of label from nock in cm",
        examples=[10.0],
    )
    model_config = ConfigDict(extra="forbid")


class ArrowsRead(ArrowsCreate):
    def get_id(self) -> UUID:
        return self.arrow_id
