from datetime import datetime
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class ShotsCreate(BaseModel):
    arrow_id: UUID = Field(..., description="ID of the arrow recorded")
    session_id: UUID = Field(..., description="ID of the session this shot belongs to")
    arrow_engage_time: datetime = Field(..., description="Filter by session start time")
    arrow_disengage_time: datetime = Field(..., description="Filter by session start time")
    arrow_landing_time: datetime | None = Field(
        default=None, description="Filter by session start time"
    )
    x: float | None = Field(default=None, description="X coordinate of the target")
    y: float | None = Field(default=None, description="Y coordinate of the target")
    model_config = ConfigDict(extra="forbid")


class ShotsFilters(BaseModel):
    shot_id: UUID | None = Field(default=None, alias="id", description="ID of the shot")
    arrow_id: UUID | None = Field(default=None, description="ID of the arrow recorded")
    session_id: UUID | None = Field(
        default=None, description="ID of the session this shot belongs to"
    )
    arrow_engage_time: datetime | None = Field(
        default=None, description="Filter by session start time"
    )
    arrow_disengage_time: datetime | None = Field(
        default=None, description="Filter by session start time"
    )
    arrow_landing_time: datetime | None = Field(
        default=None, description="Filter by session start time"
    )
    x: float | None = Field(default=None, description="X coordinate of the target")
    y: float | None = Field(default=None, description="Y coordinate of the target")

    model_config = ConfigDict(extra="forbid")


class ShotsRead(BaseModel):
    shot_id: UUID = Field(
        ...,
        alias="id",
        description="A Universally Unique Identifier generated by the system",
    )
    arrow_id: UUID = Field(..., description="ID of the arrow recorded")
    session_id: UUID = Field(..., description="ID of the session this shot belongs to")
    arrow_engage_time: datetime = Field(..., description="Filter by session start time")
    arrow_disengage_time: datetime = Field(..., description="Filter by session start time")
    arrow_landing_time: datetime | None = Field(
        default=None, description="Filter by session start time"
    )
    x: float | None = Field(default=None, description="X coordinate of the target")
    y: float | None = Field(default=None, description="Y coordinate of the target")

    model_config = ConfigDict(extra="forbid")

    def get_id(self) -> UUID:
        return self.shot_id


class ShotsUpdate(BaseModel):
    # This is a dummy class just to keep the pattern
    model_config = ConfigDict(extra="forbid")
