name: NPM Setup
description: Sets up Node and installs npm dependencies
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install dependencies
      shell: bash
      working-directory: ./frontend
      run: npm ci
