[package]
name = "server"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
postgres = { workspace = true }
ctrlc = { workspace = true }
actix-web = "*"
actix-files = "*"
