[project]
name = "target-reader"
version = "0.1.0"
description = "arch-stats: Target Reader Module"
authors = [
    { name = "Juan Pablo Molina Matute", email = "jpmolinamatute@gmail.com" },
]
requires-python = ">=3.12.7"
dependencies = []

[dependency-groups]
dev = []
