name: Frontend Linting & Formatting

on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend_linting.yaml

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node & Install Dependencies
        uses: ./.github/actions/npm-setup
      - name: Run Prettier
        run: npm run format -- --check

  lint:
    name: Run Linter (ESLint)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node & Install Dependencies
        uses: ./.github/actions/npm-setup
      - name: Run ESLint
        run: npm run lint
  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs:
      - format
      - lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node & Install Dependencies
        uses: ./.github/actions/npm-setup
      - name: Run Tests
        run: npm run test -- --watchAll=false
