name: Frontend Linting & Formatting

on:
  pull_request:
    paths:
      - frontend/**
      - .github/workflows/frontend_linting.yaml

defaults:
  run:
    shell: bash
    working-directory: ./frontend

jobs:
  format:
    name: Check Formatting (Prettier)
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node & Install Dependencies
        uses: ./.github/actions/npm-setup

      - name: Run Prettier
        run: npm run format -- --check

  lint:
    name: Run ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node & Install Dependencies
        uses: ./.github/actions/npm-setup

      - name: Run ESLint
        run: npm run lint
